ārahi	ārahi	V;ACT
ārahi	arahina	V;PASS
aroha	aroha	V;ACT
aroha	arohaina	V;PASS
aru	aru	V;ACT
aru	arumia	V;PASS
haere	haere	V;ACT
haere	haerea	V;PASS
hoki	hoki	V;ACT
hoki	hokia	V;PASS
karanga	karanga	V;ACT
karanga	karangatia	V;PASS
kite	kite	V;ACT
kite	kitea	V;PASS
mau	mau	V;ACT
mau	mauria	V;PASS
tiki	tiki	V;ACT
tiki	tikia	V;PASS
titiro	titiro	V;ACT
titiro	tirohia	V;PASS
whakanui	whakanui	V;ACT
whakanui	whakanuitia	V;PASS
āwhina	āwhina	V;ACT
āwhina	āwhinatia	V;PASS
noho	noho	V;ACT
noho	nōhia	V;PASS
tae	tae	V;ACT
tae	taea	V;PASS
whawhai	whawhai	V;ACT
whawhai	whawhaitia	V;PASS
inu	inu	V;ACT
inu	inumia	V;PASS
waiata	waiata	V;ACT
waiata	waiatatia	V;PASS
kimi	kimi	V;ACT
kimi	kimihia	V;PASS
tīmata	tīmata	V;ACT
tīmata	tīmataria	V;PASS
hanga	hanga	V;ACT
hanga	hangaia	V;PASS
āmine	āmine	V;ACT
āmine	āminetia	V;PASS
mōhio	mōhio	V;ACT
mōhio	mōhiotia	V;PASS
oma	oma	V;ACT
oma	omakia	V;PASS
tahu	tahu	V;ACT
tahu	tahuna	V;PASS
tunu	tunu	V;ACT
tunu	tunua	V;PASS
tao	tao	V;ACT
tao	taona	V;PASS
kōwhiti	kōwhiti	V;ACT
kōwhiti	kōwhitia	V;PASS
pīrangi	pīrangi	V;ACT
pīrangi	pīrangitia	V;PASS
kī	kī	V;ACT
kī	kīa	V;PASS
whakarongo	whakarongo	V;ACT
whakarongo	whakarongona	V;PASS
tuhituhi	tuhituhi	V;ACT
tuhituhi	tuhituhia	V;PASS
rongo	rongo	V;ACT
rongo	rangona	V;PASS
noho	noho	V;ACT
noho	nōhia	V;PASS
horoi	horoi	V;ACT
horoi	horoia	V;PASS
kai	kai	V;ACT
kai	kainga	V;PASS
whāngai	whāngai	V;ACT
whāngai	whāngaia	V;PASS
kōrero	kōrero	V;ACT
kōrero	kōrerotia	V;PASS
tuku	tuku	V;ACT
tuku	tukua	V;PASS
tangi	tangi	V;ACT
tangi	tangihia	V;PASS
ua	ua	V;ACT
ua	uaina	V;PASS
pātai	pātai	V;ACT
pātai	pātaitia	V;PASS
kohikohi	kohikohi	V;ACT
kohikohi	kohikohia	V;PASS
mahara	mahara	V;ACT
mahara	maharatia	V;PASS
tūtaki	tūtaki	V;ACT
tūtaki	tūtakitia	V;PASS
hiahia	hiahia	V;ACT
hiahia	hiahiatia	V;PASS
mahi	mahi	V;ACT
mahi	mahia	V;PASS
ora	ora	V;ACT
ora	orangia	V;PASS
rere	rere	V;ACT
rere	rerea	V;PASS
akiri	akiri	V;ACT
akiri	akiritia	V;PASS
ako	ako	V;ACT
ako	ākona	V;PASS
ārahi	ārahi	V;ACT
ārahi	arahina	V;PASS
eke	eke	V;ACT
eke	ekea	V;PASS
hākari	hākari	V;ACT
hākari	hākaritia	V;PASS
hamu	hamu	V;ACT
hamu	hamua	V;PASS
hari	hari	V;ACT
hari	haria	V;PASS
wharirū	wharirū	V;ACT
wharirū	wharirūtia	V;PASS
hau	hau	V;ACT
hau	hāua	V;PASS
hemo	hemo	V;ACT
hemo	hemoa	V;PASS
hiki	hiki	V;ACT
hiki	hīkina	V;PASS
hīkoi	hīkoi	V;ACT
hīkoi	hīkoitia	V;PASS
hinga	hinga	V;ACT
hinga	hingaia	V;PASS
hoe	hoe	V;ACT
hoe	hoea	V;PASS
hoki	hoki	V;ACT
hoki	hokia	V;PASS
hoko	hoko	V;ACT
hoko	hokona	V;PASS
hono	hono	V;ACT
hono	honoa	V;PASS
hora	hora	V;ACT
hora	horahia	V;PASS
horomiti	horomiti	V;ACT
horomiti	horomititia	V;PASS
hui	hui	V;ACT
hui	huia	V;PASS
hūtuki	hūtuki	V;ACT
hūtuki	hūtukia	V;PASS
kati	kati	V;ACT
kati	katia	V;PASS
kau	kau	V;ACT
kau	kauria	V;PASS
kaukau	kaukau	V;ACT
kaukau	kaukauria	V;PASS
keri	keri	V;ACT
keri	keria	V;PASS
kini	kini	V;ACT
kini	kinia	V;PASS
kutētē	kutētē	V;ACT
kutētē	kutētētia	V;PASS
manaaki	manaaki	V;ACT
manaaki	manaakitia	V;PASS
mauāhara	mauāhara	V;ACT
mauāhara	mauāharatia	V;PASS
mauhere	mauhere	V;ACT
mauhere	mauheretia	V;PASS
maunu	maunu	V;ACT
maunu	maunuhia	V;PASS
mihi	mihi	V;ACT
mihi	mihia	V;PASS
motu	motu	V;ACT
motu	motukia	V;PASS
mutu	mutu	V;ACT
mutu	mutua	V;PASS
nehu	nehu	V;ACT
nehu	nehua	V;PASS
neke	neke	V;ACT
neke	nekehia	V;PASS
oho	oho	V;ACT
oho	ohokia	V;PASS
oka	oka	V;ACT
oka	okaina	V;PASS
pā	pā	V;ACT
pā	pāngia	V;PASS
momotu	momotu	V;ACT
momotu	motukia	V;PASS
pānui	pānui	V;ACT
pānui	pānuitia	V;PASS
paki	paki	V;ACT
paki	pākia	V;PASS
parai	parai	V;ACT
parai	paraitia	V;PASS
patu	patu	V;ACT
patu	patua	V;PASS
pī	pī	V;ACT
pī	pīhia	V;PASS
puta	puta	V;ACT
puta	putaina	V;PASS
rite	rite	V;ACT
rite	ritea	V;PASS
ruaki	ruaki	V;ACT
ruaki	ruakina	V;PASS
ruku	ruku	V;ACT
ruku	rukuhia	V;PASS
ruruku	ruruku	V;ACT
ruruku	rurukutia	V;PASS
tahi	tahi	V;ACT
tahi	tahia	V;PASS
takahi	takahi	V;ACT
takahi	takahia	V;PASS
tākaro	tākaro	V;ACT
tākaro	tākarohia	V;PASS
tango	tango	V;ACT
tango	tangohia	V;PASS
tomo	tomo	V;ACT
tomo	tomokia	V;PASS
tono	tono	V;ACT
tono	tonoa	V;PASS
tuitui	tuitui	V;ACT
tuitui	tuituia	V;PASS
tupu	tupu	V;ACT
tupu	tupuria	V;PASS
wareware	wareware	V;ACT
wareware	warewaretia	V;PASS
